server:
  port: 8095

spring:
  application:
    name: york-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  #
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

zuul:
  routes:
    api-a:
      path: /api-c/**
      serviceId: york-ribbon
    api-b:
      path: /api-d/**
      serviceId: york-feign
