server:
  port: 8094

spring:
  application:
    name: york-ribbon

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  #
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}